apiVersion: v1
kind: ReplicationController
metadata: 
 name: javawebapprc
spec: 
 replica: 1
selector:
 app: javawebapp
templete: 
 metadata:
  name: javawebapppod
  labels:
   app: javawebapp
 spec:
  containers:
    - name: javawebappcontainer
      image: ashokit/javawebapp
      ports:
       - containerPort: 8080
---
#### NodePort Manifest file#######
apiVersion: v1
kind: Service
metadata:
  name: javawebappnpsrc
spec: 
  type: NodePort
  selector:
   app: javawebapp
   ports:
    - port: 80
      containerPort: 8080   



