apiVersion: apps/v1
kind: Deployment
metadata: 
  name: javawebapprecreatdeployment
  labels:
    app: javawebapp
spec:
  replicas: 4
  strategy:
    type: recreat
  selector: 
     matchLabels:
       app: javawebapp
  template:
   metadata:
     name: javawebappdeploymentpod
     labels:
       app: javawebapp
   spec:
    containers:
      - name: javawebappdeploymentcontainer
        image: ashokit/javawebapp
        ports:
         - containerPort: 8080

---
### NodePort service manifest file ####
apiVersion: v1
kind: Service
metadata:
 name: javawebappnpdeploymentservice
spec: 
  type: LoadBalancer
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080



