apiVersion: v1
kind: ResourceQuota
metadata:
 name: apple-ns-quota
 namespace: apple
spec:
 hard:
   #compute-resources
   requests.cpu: "1000m"
   limits.cpu: "2000m"
   requests.memory: 1Gi
   limits.memory: 2Gi
   #object-counts
   count/deployments.apps: "1"
   count/pods: "4"
   count/replicasets.apps: "1"
   count/secrets: "4"
   count/services: "1"

---
### Resource Quota for Windows NS###
apiVersion: v1
kind: ResourceQuota
metadata:
 name: windows-ns-quota
 namespace: windows
spec:
 hard:
   #compute-resources
   requests.cpu: "1000m"
   limits.cpu: "2000m"
   requests.memory: 1Gi
   limits.memory: 2Gi
   #object-counts
   count/deployments.apps: "1"
   count/pods: "4"
   count/replicasets.apps: "1"
   count/secrets: "4"
   count/services: "1"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
spec:
  limits:
  - type: Pod
    max:
      cpu: 2
      memory: 1Gi
    min:
      cpu: 200m
      memory: 64Mi
  - type: Container
    max:
      cpu: 2
      memory: 1Gi
    min:
      cpu: 100m
      memory: 4Mi   
    default: 
      cpu: 300m 
      memory: 200Mi
    defaultRequest: 
      cpu: 200m
      memory: 100Mi
    maxLimitRequestRatio:
      cpu: 10 