apiVersion: apps/v1    ##specify the Kubernetes resource type as a Deployment
kind: Deployment      ##resource you are defining within that file
metadata:             ##specify the Kubernetes resource type as a Deployment
  name: javawebappdeployment    ##name: Specifies the name of the resource. Names must be unique within a namespace for most resource types. The name field is mandatory.
  labels:  ##Allows you to attach arbitrary key-value pairs (metadata) to the resource. Labels are used for grouping and selecting resources, and they are essential for creating selectors that define how resources are selected and matched.
    app: javawebapp
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxSurge: 1  ##The maximum number of new pods that can be created during an update##
     maxUnavailable: 3  ## # The maximum number of old pods that can be unavailable during an update##
  selector:
     matchLabels:
       app: javawebapp
  template:
   metadata:
     name: javawebappdeploymentpod
     labels:
       app: javawebapp
   spec:
    containers:
      - name: javawebappdeploymentcontainer
        image: ashokit/javawebapp
        ports:
         - containerPort: 8080

---
### NodePort service manifest file ####
apiVersion: v1
kind: Service
metadata:
 name: javawebappnpdeploymentservice
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080




