apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscli-deploymentnew
  labels:
    app: awscli1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awscli1
  template:
    metadata:
      labels:
        app: awscli1
    spec:
      containers:
        - name: awscli1
          image: sreeharshav/utils:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-keys
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-access-keys
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom: "us-east-1"
