apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp01
  name: myapp01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp01
  template:
    metadata:
      labels:
        app: myapp01
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v5
        name: rollingupdate
      nodeSelector:
        kubernetes.io/hostname: i-00a968443bbbdd1cf

#kubectl get pods -o wide --no-headers |  awk -F"  " '{print $1 $8}'
#ku label node <node-ip> high-perf-cpu=yes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp02
  name: myapp02
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp02
  template:
    metadata:
      labels:
        app: myapp02
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v1
        name: rollingupdate
      nodeSelector:
        high-perf-cpu: "yes"
