apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydepl
  name: mydepl
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mydepl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydepl
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v1
        name: rollingupdate

