apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: blue
      version: v1
      colour: blue
  template:
    metadata:
      labels:
        app: blue
        version: v1
        colour: blue
    spec:
      containers:
        - name: blue
          image: naveenbabuch/rollingupdate:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: blue
spec:
  type: NodePort
  selector:
    app: blue
    version: v1
  ports:
    - port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: green
      version: v1
      colour: green  
  template:
    metadata:
      labels:
        app: green
        version: v1
        colour: green  
    spec:
      containers:
        - name: green
          image: nginx:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  type: NodePort
  selector:
    app: green
    version: v1
  ports:
    - port: 80
      
