
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
spec:
  selector:
    matchLabels:
     app: javawebappdaemonset
  template:
    metadata:
      #name: javawebapp-pod
      labels:
        app: javawebappdaemonset
    spec:
      containers:
        - name: javawebappdaemonsetcontainer
          image: ashokit/javawebapp
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappdaemonsetnpservice
spec:
  type: NodePort
  selector:
    app: javawebappdaemonset
  ports:
    - port: 80
      targetPort: 8080


