apiVersion : apps/v1
kind: Deployment
metadata:
 name: k8s-boot-demo-deployment-green    ##name of the deployment & Pod's name also, bcz pods will create with replicas.
spec:
 replicas: 3
 strategy:
  type: RollingUpdate
 selector:
  matchLabels:
   app: k8s-boot-demo
   version: v2
   colour: green
   #####below stpes for pod creation####
 template:
   metadata:
    labels:
     app: k8s-boot-demo
     version: v2
     colour: green
   spec:
     containers:
      - name: k8s-boot-demo
        image: ashokit/javawebapp
        ports:
         - containerPort: 8080
---
#### manifest file for Service creation ######
apiVersion : v1
kind : Service
metedata: 
 name: k8s-boot-demo-service-preproduction
spec: 
 type: NodePort
selector:
 app: k8s-boot-demo
 version: v2
ports:
##- name: java-wb-port-mapping
   ##protocol: TCP
 - port: 80
   targetPort: 8080          
   ##nodePort: 33390