apiVersion: apps/v1
kind: Deployment
metadata: 
  name: Recreat-deployment
  labels:
    app: javawebapp
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector: 
     matchLabels:
       app: javawebapp
  template:
   metadata:
     name: javawebappdeploymentpod
     labels:
       app: javawebapp
  spec:
    containers:
      - name: javawebappdeploymentcontainer
        image: sreeharshav/rollingupdate:v5
        ports:
         - containerPort: 8080
---
### NodePort service manifest file ####
apiVersion: v1
kind: Service
metadata:
 name: javawebappnpdeploymentservice 
spec: 
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
---



