apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydepl
  name: mydepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydepl
  strategy:
   type: Recreate
  template:
    metadata:
      labels:
        app: mydepl
    spec:
      containers:
      - image: naveenbabuch/rollingupdate:latest
        name: rollingupdate

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mydepl
  name: mydepl
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: mydepl
  type: NodePort
        