apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapprc
spec:
  replicas: 3
  selector:
    matchLabels:
     app: javawebapp
     
  template:
    metadata:
      name: javawebapp-pod
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebapp-container
          image: ashokit/javawebapp
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp-npsrc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
