apiVersion: v1
kind: ReplicationController
metadata: 
 name: javawebapprc
spec: 
 replicas: 3  # Corrected from 'replica' to 'replicas'
 selector:
   app: javawebapp
 template:  # Corrected from 'templete' to 'template'
   metadata:
    name: javawebapppod
    labels:
     app: javawebapp
   spec:
    containers:
      - name: javawebappcontainer
        image: ashokit/javawebapp
        ports:
         - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp-npsrc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
         
